arb-dir: lib/l10n
template-arb-file: app_en.arb
output-dir: lib/l10n/generated
output-localization-file: app_localizations.dart
untranslated-messages-file: .untranslated-messages.json
nullable-getter: false
