name: Build Next

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read
    uses: ./.github/workflows/build.yml
    with:
      gradle-args: ":app:assembleDebug :app:assembleNext --no-daemon"
      artifact-name: subtracks-next
      artifact-path: app/build/outputs/apk
