name: Build Nightly

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-26.04
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: ./.github/actions/build
        with:
          gradle-args: ":app:assembleDebug :app:assembleNightly --no-daemon"
      - name: Checksums
        run: sha256sum app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/nightly/app-nightly.apk
      - uses: actions/upload-artifact@v7
        with:
          name: subtracks-nightly
          path: app/build/outputs/apk
